### ISSUE TITLE
changing some texts

### ISSUE THREAD

**Issue by resonancecode** [PengWang0316/ResonanceCode#107]
Particle Line 1/3  --> Hard Reality Line 1/3
Wave Line 4/6 --> Soft Reality Line 4/6

Agency/Process Line 1/4 --> Process/Agency Line 1/4
Agent/Perspective Line 3/6 --> Perspective/Agent Line 3/6
Resonance/Context Line 2/5 --> Resonance Cycle Line 2/5

**Comment by PengWang0316** [comment]
Resolved by #108
