### ISSUE TITLE
Input text

### ISSUE THREAD

**Issue by resonancecode** [PengWang0316/ResonanceCode#114]
When I input information for the hexagrams, is there a way for the input box to recognize line break automatically? Right now I need to manually add in the line break

**Comment by PengWang0316** [comment]
Did not show the problem when I tried to copy text from Word.
![image](https://user-images.githubusercontent.com/24322974/38771264-e60896d6-3fd4-11e8-9a40-855c6c7d45cf.png)

**Comment by resonancecode** [comment]
Yes, when I copy the texts from word document

**Comment by PengWang0316** [comment]
Please reopen it if still encounter this problem.
