### ISSUE TITLE
Add changing lines

### ISSUE THREAD

**Issue by resonancecode** [PengWang0316/ResonanceCode#38]
[Line Change Spec.docx](https://github.com/PengWang0316/ResonanceCode/files/1713804/Line.Change.Spec.docx)

**Comment by PengWang0316** [comment]
![image](https://user-images.githubusercontent.com/24322974/36070082-b7f40fbc-0ea8-11e8-99b1-5ba785fb5208.png)
![image](https://user-images.githubusercontent.com/24322974/36070116-21501fdc-0ea9-11e8-8bc0-a5e30cda632b.png)
![image](https://user-images.githubusercontent.com/24322974/36070121-2f620892-0ea9-11e8-81b9-bd4cb9a8b671.png)

**Comment by PengWang0316** [comment]
- No need to show the original hexagram.
- Changing hexagram should use small size
