### ISSUE TITLE
Refinement of the Hexagram Page

### ISSUE THREAD

**Issue by resonancecode** [PengWang0316/ResonanceCode#42]
1. Put question before analysis
2. Put the Resonance Code Name on the top line. Change the color to match the logo color
3. Move the I-Ching Name to the position of the original RC name. Change the font to a greyer one
4. No need to show # twice in the header portion
See example
![image](https://user-images.githubusercontent.com/36137351/36076073-796de7c2-0f0c-11e8-8a1f-232ff339d32e.png)

**Comment by PengWang0316** [comment]
Resolved by #44
