### ISSUE TITLE
Fine adjustment of the display

### ISSUE THREAD

**Issue by resonancecode** [PengWang0316/ResonanceCode#47]
![image](https://user-images.githubusercontent.com/36137351/36116754-2bf8ce9a-0fec-11e8-8504-6d80a6e6d002.png)

1. The horizontal labels Agent/Identity on the left and right side of the table are not aligned. 
2. Taking out the "-": and center the two lines:

Agent/Identity
    Being

**Comment by PengWang0316** [comment]
- Changing the title line to grayer color.
- Changing the poetry font to @import url('https://fonts.googleapis.com/css?family=Caveat');
